Do not instantiate the Runtime in crash reporter service
Currently the CrashReporter service uses the runtime to create a
CrashReportIntent. The reason why it does that is because the CrashReportIntent
receives some parameters that depend on the backend (Gecko,Chromium) which
cannot be resolved at build time.

By the time the CrashReporter creates that intent the runtime might not exist
(like after a crash in the application). This means that the service will try
to create it. The problem is that creating the runtime might not be possible,
for example the GeckoRuntime must be created in the main thread but the crash
reporter service is run in an async task as it can be see in this backtrace:

2022-09-08 14:15:38.005 20233-20267/com.igalia.wolvic.dev E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.igalia.wolvic.dev:crash, PID: 20233
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 930 ("AsyncTask #1")
        at org.mozilla.gecko.util.ThreadUtils.assertOnThreadComparison(ThreadUtils.java:127)
        at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:93)
        at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:84)
        at org.mozilla.geckoview.GeckoRuntime.create(GeckoRuntime.java:552)
        at com.igalia.wolvic.browser.api.impl.RuntimeImpl.<init>(RuntimeImpl.java:72)
        at com.igalia.wolvic.browser.api.WFactory.createRuntime(WFactory.java:14)
        at com.igalia.wolvic.browser.engine.EngineProvider.getOrCreateRuntime(EngineProvider.kt:67)
        at com.igalia.wolvic.crashreporting.CrashReporterService.onHandleWork(CrashReporterService.java:65)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

This is why we have to add an extra class per backend that is able to create
those intents without having to instantiate the runtime.

Signed-off-by: Songlin Jiang <sjiang@igalia.com>